#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LearningApp1.Resource", IsApplication=true)]

namespace LearningApp1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bussmall = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int coffee = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int person = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050040
			public const int accelBlackoutSwitch = 2131034176;
			
			// aapt resource value: 0x7f050000
			public const int accelStatus = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int accelStrength = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int accelX = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int accelY = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int accelZ = 2131034116;
			
			// aapt resource value: 0x7f05002d
			public const int acknowledged = 2131034157;
			
			// aapt resource value: 0x7f050041
			public const int ambientLight = 2131034177;
			
			// aapt resource value: 0x7f050033
			public const int blackout = 2131034163;
			
			// aapt resource value: 0x7f050039
			public const int blackoutAccelX = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int blackoutAccelY = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int blackoutAccelZ = 2131034171;
			
			// aapt resource value: 0x7f05002c
			public const int breaktime = 2131034156;
			
			// aapt resource value: 0x7f050047
			public const int button1 = 2131034183;
			
			// aapt resource value: 0x7f050046
			public const int button2 = 2131034182;
			
			// aapt resource value: 0x7f050036
			public const int currentSpeed = 2131034166;
			
			// aapt resource value: 0x7f050012
			public const int gpsAccuracy2 = 2131034130;
			
			// aapt resource value: 0x7f05003f
			public const int gpsBlackoutSwitch = 2131034175;
			
			// aapt resource value: 0x7f050017
			public const int gpsContact2 = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int gpsCount2 = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int gpsLastUpdate2 = 2131034136;
			
			// aapt resource value: 0x7f05000e
			public const int gpsLatitude = 2131034126;
			
			// aapt resource value: 0x7f050013
			public const int gpsLatitude2 = 2131034131;
			
			// aapt resource value: 0x7f05000f
			public const int gpsLongitude = 2131034127;
			
			// aapt resource value: 0x7f050014
			public const int gpsLongitude2 = 2131034132;
			
			// aapt resource value: 0x7f05000d
			public const int gpsProvider = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int gpsSpeed = 2131034128;
			
			// aapt resource value: 0x7f050015
			public const int gpsSpeed2 = 2131034133;
			
			// aapt resource value: 0x7f05000c
			public const int gpsStatus = 2131034124;
			
			// aapt resource value: 0x7f050011
			public const int gpsStatus2 = 2131034129;
			
			// aapt resource value: 0x7f050016
			public const int gpsTime2 = 2131034134;
			
			// aapt resource value: 0x7f050042
			public const int imageView1 = 2131034178;
			
			// aapt resource value: 0x7f05002e
			public const int linearLayout1 = 2131034158;
			
			// aapt resource value: 0x7f050043
			public const int linearLayout2 = 2131034179;
			
			// aapt resource value: 0x7f050045
			public const int linearLayout3 = 2131034181;
			
			// aapt resource value: 0x7f050005
			public const int linearStatus = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int linearStrength = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int linearX = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int linearY = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int linearZ = 2131034121;
			
			// aapt resource value: 0x7f050023
			public const int loginUser1Button = 2131034147;
			
			// aapt resource value: 0x7f050026
			public const int loginUser2Button = 2131034150;
			
			// aapt resource value: 0x7f05002a
			public const int logintime = 2131034154;
			
			// aapt resource value: 0x7f050025
			public const int logoutUser1Button = 2131034149;
			
			// aapt resource value: 0x7f050028
			public const int logoutUser2Button = 2131034152;
			
			// aapt resource value: 0x7f05001b
			public const int networkAccuracy = 2131034139;
			
			// aapt resource value: 0x7f050020
			public const int networkContact = 2131034144;
			
			// aapt resource value: 0x7f050022
			public const int networkCount = 2131034146;
			
			// aapt resource value: 0x7f050021
			public const int networkLastUpdate = 2131034145;
			
			// aapt resource value: 0x7f05001c
			public const int networkLatitude = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int networkLongitude = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int networkSpeed = 2131034142;
			
			// aapt resource value: 0x7f05001a
			public const int networkStatus = 2131034138;
			
			// aapt resource value: 0x7f05001f
			public const int networkTime = 2131034143;
			
			// aapt resource value: 0x7f050032
			public const int overallLayout = 2131034162;
			
			// aapt resource value: 0x7f050034
			public const int subLayout1 = 2131034164;
			
			// aapt resource value: 0x7f050037
			public const int subLayout2 = 2131034167;
			
			// aapt resource value: 0x7f05003d
			public const int subLayout3 = 2131034173;
			
			// aapt resource value: 0x7f05000a
			public const int textView1 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int textView2 = 2131034123;
			
			// aapt resource value: 0x7f050044
			public const int textView3 = 2131034180;
			
			// aapt resource value: 0x7f05003c
			public const int threshold = 2131034172;
			
			// aapt resource value: 0x7f050024
			public const int timeWorked1 = 2131034148;
			
			// aapt resource value: 0x7f050027
			public const int timeWorked2 = 2131034151;
			
			// aapt resource value: 0x7f05002b
			public const int timeworked = 2131034155;
			
			// aapt resource value: 0x7f050035
			public const int title1 = 2131034165;
			
			// aapt resource value: 0x7f050038
			public const int title2 = 2131034168;
			
			// aapt resource value: 0x7f05003e
			public const int title3 = 2131034174;
			
			// aapt resource value: 0x7f050031
			public const int toAccelerometer = 2131034161;
			
			// aapt resource value: 0x7f05002f
			public const int toGPSNetTest = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int toMotionStop = 2131034160;
			
			// aapt resource value: 0x7f050029
			public const int username = 2131034153;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AccelerometerMain = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GPSNetMain = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MotionStopMain = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_large = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
